<form method="get" class="form-horizontal">
	<div class="modal fade" tabindex="-1" role="dialog" id="page-search">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h4 class="modal-title">
						<i class="fa fa-lock" aria-hidden="true"></i>
					<?php echo $this->translate('Page Search'); ?></h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label for="pageRoute" class="col-sm-2 control-label"><?php echo $this->translate("Route")?></label>
						<div class="col-sm-10">
							<input type="text" class="form-control" id="pageRoute" name="pageRoute" value="<?php echo $this->queryParams["pageRoute"]; ?>">
						</div>
					</div>
				
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
					<button type="submit" class="btn btn-primary"><?php echo $this->translate('Search'); ?></button>
				</div>
			</div>
		</div>
	</div>
</form>